### ISSUE TITLE
bug: attribute selector makes px2rem panic

### ISSUE THREAD

**Issue by PeachScript** [umijs/mako#1137]
开启 px2rem 且存在属性选择器时，会报 panic：

```bash
Building with mako for development...
thread 'rayon thread 0' panicked at crates/mako/src/visitors/css_px2rem.rs:198:26:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
[1]    92575 abort      cargo run --bin mako e2e/fixtures/config.px2rem
```

复现写法：

```css
h1[title] {
  color: red;
}

/* 属性带值的情况下是可以过的 */
h1[title=1] {
  color: red;
}
```
