### ISSUE TITLE
bug: ambiguous css modules

### ISSUE THREAD

**Issue by PeachScript** [umijs/mako#1677]
同一段代码：

```css
.foo {
  &:global.bar {
    color: #fff;
    .hey {
      color: #fff;
    }
  }
}
```

在 `mako@0.8.x` 中会编译成：

```css
.foo-xxx.bar {
  color: #fff;
}
.foo-xxx.bar .hey {
  color: #fff;
}
```

但在 `mako@0.9.x` 中会编译成：

```css
.foo-xxx.bar-yyy {
  color: #fff;
}
.foo-xxx.bar-yyy .hey {
  color: #fff;
}
```

`:global.xx` 并非 [CSS Modules 文档](https://github.com/css-modules/css-modules/blob/master/docs/composition.md#exceptions)中提到的用法，不知道是否是 undefined behavior，需要对比 css-loader 来确认是 SWC CSS 的 bug 还是规范以外的用法，以及确认实现同等语义的正确范式应该是怎样的。

另外 `mako@0.9.x` 还有一些『诡异』（不确定正确结果应该是什么）的行为，比如：

```css
.foo {
  :global {
    &.bar {
      color: #fff;
    }
  }
}
// 会被编译成
.foo-yyy {
 color: #fff;
}
```
