### ISSUE TITLE
bug: less兼容问题 Tsfn promise rejected GenericFailure, Error: OperationError: Operation on an invalid type

### ISSUE THREAD

**Issue by rendeyuwei** [umijs/mako#1701]
只需用umi的脚手架创建出一个初始项目，然后加入一段这样的less样式并引入，就会报错：
```less
.test {
  top: 8px + 16px / 2;
}
```
但是这样写就不会报错`8px + (16px / 2)`

![image](https://github.com/user-attachments/assets/00297d4c-f1f9-410d-ace3-9d788bc2779a)
