### ISSUE TITLE
期望支持数字类型的 class name

### ISSUE THREAD

**Issue by hualigushi** [umijs/mako#1724]
期望支持如下写法的样式
```
.404 {
  margin: 0 24px;
  padding-bottom: 40px;
}
```

**Comment by stormslowly** [comment]
我记得 `.404` 在 css 中就是一个非法的选择器名字

**Comment by stormslowly** [comment]
需要转义下
```css
.\34 04 {
  color: yellow;
}
```

```js
 '4'.charCodeAt(0).toString(16)   // 34
```
