### ISSUE TITLE
css modules 不支持 :global scope

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#221]
复现步骤，

```css
.a {
  color: red;
}

:global {
  .b {
    color: green;
  }
}
```

会报错，

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: SelectorError(EmptySelector), loc: Some(ErrorLocation { filename: "", line: 3, column: 2 }) }', crates/mako/src/transform_in_generate.rs:62:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

:local 应该也同理，我没测。
