### ISSUE TITLE
CSS import 资源文件时不支持不带 ./ 的方式

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#241]
```css
.title {
  background: url(big.jpg);
}
```

现在会报 Resolve 找不到。

```css
.title {
  background: url(./big.jpg);
}
```

加上 ./ 才正确。

而实际上，CSS 里通过 url 的方式引用资源，是不需要带 ./ 的，也会从相对路径开始找。
