### ISSUE TITLE
CSS 语法错误不会提示

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#357]
比如，

```css
.foo \{ color: red; }
```

{ 之前多写了个 \，应该是语法错误。

Farm 会提示，Rspack 不会提示，Mako 也不会提示。
