### ISSUE TITLE
less 未兼容错误语法

### ISSUE THREAD

**Issue by stormslowly** [umijs/mako#560]
detail ： mako/vz2gn4/mn3il56gdgb1azsl#TgkId 

```less
  .ant-dropdown-trigger.extra {
    position: absolute;
    right: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 100%;

    &:hover {
      color: #3471f9;
      background-color: rgba(64 121, 249, 0.08);   
    }
  }
```
mako 报错
```txt
  × Expected percentage, number, function (math functions) or ident (with 'none' value) token
    ╭─[../node_modules/@alipay/tech-vis/es/components/Tooltip/components/Header/index.less:69:1]
 69 │ }
 70 │ .techvis-tooltip-header-actions-item:hover {
 71 │   color: #3471f9;
 72 │   background-color: rgba(64 121, 249, 0.08);
    ·                                ─
 73 │ }
 74 │ .techvis-tooltip-header .ant-dropdown-trigger.extra {
 75 │   position: absolute;
    ╰────
```

<del>webpack 正常编译，产物补全了语法</del> 
<del>
.techvis-tooltip-header .ant-dropdown-trigger.extra:hover {
  color: #3471f9;
  background-color: rgba(64, 121, 249, 0.08);
}
</del>

update: 没有补全，是我为了验证项目手动补全，误以为是 webpack 做的。
