### ISSUE TITLE
feature request：支持 source map 合并

### ISSUE THREAD

**Issue by jiesia** [umijs/mako#758]
支持 sourcemap 合并，现在 less 编译生成的 sourcemap 没有跟 swc 编译 css 生成的 sourcemap 合并，导致在 devtool 中看到的 less 源码其实是编译后的 css：

```less
// index.less

h1 {
  color: red;

  .blue {
    color: blue;
  }
}
```
<img width="499" alt="image" src="https://github.com/umijs/mako/assets/74305323/14906f75-d61b-4820-ab14-1aadb0f42ae3">
