### ISSUE TITLE
Bug：css modules + :global + & 时，部分选择器丢失的问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#904]
> 注：和 less 无关。

问题，

```css
:global(li):not(.title).active {
  color: green;
}
:global(li):not(.title):hover {
  color: red;
}
```

0.4.1 之后由于升级了 SWC 会被编译成，

```css
li:not(.title-nByczzOD) { color: green; }
li:not(.title-nByczzOD) { color: red; }
```

0.4.0

```css
li:not(.title-o9UXvAH7).active { color: green; }
li:not(.title-o9UXvAH7):hover { color: red; }
```

期望，

```css
li:not(.title___xEd86).active___qEVYZ {
  color: green;
}
li:not(.title___xEd86):hover {
  color: red;
}
```

所以，有两个问题，

1、.active selector 或 :hover 伪类丢失
2、旧版本的 .active 在旧版本虽然没有丢失，但没有加上 css modules 的 hash

相关问题：
https://github.com/swc-project/swc/issues/8461

注1：试了下 @rsbuild/core@0.3.11，一样有这个问题。
注2：

```css
.foo:global(.bar).baz {
  color: red;
}
```

会丢失 `.baz` 。
