### ISSUE TITLE
Bug：css modules + :global + 伪类函数里选择器没有 x 的问题

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#905]
问题，

```css
:global .a:has(.b) {
  color: green;
}
```

会被编译成，

```css
.a:has(.b-uqwDedAi) { color: green; }
```

期望，

```css
.a:has(.b) { color: green; }
```
