### ISSUE TITLE
Bug：css modules 的 :global/:local + 引号的写法会导致内存溢出

### ISSUE THREAD

**Issue by sorrycc** [umijs/mako#973]
最简复现：

a.module.css

```css
.a {
  :global('.b') {
    color: red;
  }
}
```

会导致内存泄漏，然后卡死。

删除引号就好了。

```css
.a {
  :global(.b) {
    color: red;
  }
}
```

排查 with @stormslowly 。
